# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Applies Binary Segmentation Algorithm to the given data data_vec
#'
#' \code{apply_binseg} returns the status of a successful Binary Segmentation algorithm on the given parameters.
#' Most of the passed parameters are set for the result.
#'
#' @param data_vec The 1 dimensional input chromosome data
#' @param kmax Maximum number of segments to divide.
#' @return Status code of the algorithm.
#'
#'   For description of how Binseg algorithm works, please see the following url.
#'   \url{https://arxiv.org/abs/1801.00718}
#' @examples
#' apply_binseg(c(0.1, 0, 1, 1.1, 0.1, 0), 3)
#' @export
apply_binseg <- function(data_vec, kmax) {
    .Call(`_Segmentation_apply_binseg`, data_vec, kmax)
}

